name: "Schedule-branch"

on:
  push:
    branches:
    - '**'

jobs:
  call-build-and-test:
    name: Run
    uses: ./.github/workflows/test.yml
    with:
      java: 8
      branch: branch-3.2
      cron: true
