name: "Schedule-branch"

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  call-build-and-test:
    name: Run
    uses: ./.github/workflows/test.yml
    with:
      java: 8
      branch: branch-3.2
      cron: true
