name: "Build"

on:
  push:
    branches:
    - '**'

jobs:
  call-build-and-test:
    name: Run
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      java: 8
      branch: master
      cron: false
