name: "Schedule master"

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  call-build-and-test:
    name: Run
    uses: ./.github/workflows/test.yml
    with:
      java: 8
      branch: master
      cron: true
